"""create pos

Revision ID: 01051ff3c082
Revises: 7a2500e53bc3
Create Date: 2020-12-15 21:33:59.209229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01051ff3c082'
down_revision = '7a2500e53bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=150), nullable=False),
    sa.Column('thrumb_url', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_posts_create_time'), 'tb_posts', ['create_time'], unique=False)
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_tb_users_create_time'), 'tb_users', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_users_create_time'), table_name='tb_users')
    op.drop_table('tb_users')
    op.drop_index(op.f('ix_tb_posts_create_time'), table_name='tb_posts')
    op.drop_table('tb_posts')
    # ### end Alembic commands ###
