"""create tb_users

Revision ID: 2c0321b94d9c
Revises: 4cc5b49a5652
Create Date: 2020-12-15 15:37:12.528308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0321b94d9c'
down_revision = '4cc5b49a5652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
