"""create tb_posts

Revision ID: 4694e43cb4eb
Revises: ff8b56665d09
Create Date: 2020-12-15 21:27:09.491340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4694e43cb4eb'
down_revision = 'ff8b56665d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
