"""create tb_users

Revision ID: 4cc5b49a5652
Revises: 7edb1e78a303
Create Date: 2020-12-15 15:31:19.004775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc5b49a5652'
down_revision = '7edb1e78a303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
