"""create tb_users

Revision ID: 63e71ac9579a
Revises: 2c0321b94d9c
Create Date: 2020-12-15 15:37:39.759104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e71ac9579a'
down_revision = '2c0321b94d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
