"""create wocao

Revision ID: 7a2500e53bc3
Revises: 4694e43cb4eb
Create Date: 2020-12-15 21:27:23.248868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2500e53bc3'
down_revision = '4694e43cb4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
