"""create tb_posts and tb_users

Revision ID: 7dac2c37c100
Revises: 01051ff3c082
Create Date: 2020-12-15 21:40:30.289019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dac2c37c100'
down_revision = '01051ff3c082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_posts', 'tb_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_posts', type_='foreignkey')
    op.drop_column('tb_posts', 'user_id')
    # ### end Alembic commands ###
